#!/usr/bin/env bash

killall polybar
killall picom
killall sxhkd
killall unclutter
killall xidlehook
picom -b 
setxkbmap -layout us,ru -option grp:alt_shift_toggle
sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
unclutter --timeout 60 &
dunst &
xset dpms 0 0 0
xset s off
xidlehook \
	--timer 1200 \
	'xset dpms force off' \
	'' \
	--timer 60 \
	'betterlockscreen -l dimblur --off 60' \
	'' \
	--timer 2340 \
	'systemctl suspend; xset dpms force on' \
	'' &
polybar top &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#817f7f"
bspc config presel_feedback_color "#f4d775"

bspc rule -a \* center=true
bspc rule -a Nitrogen state=floating
bspc rule -a torbrowser-launcher state=floating
